### ISSUE TITLE
Installation Prerequisites Unclear

### ISSUE THREAD

**Issue by birbofathena** [Tawling/MultiPause#3]
The readme warns that this mod uses Harmony to edit the game's `shouldTimePass()` method — "Harmony" being hyperlinked to its own repo. To me, this suggests that I must install Harmony before installing this mod. Is this the case?

**Comment by Velgus** [comment]
Harmony is just the framework the mod uses to allow it to alter game code. You don't have to install anything separate, the library is included with the mod install (the 0Harmony.dll file).

**Comment by birbofathena** [comment]
Ah, sorry about that. I was totally looking in the wrong place. Thanks for the response!
