### ISSUE TITLE
MultiPause.dll missing

### ISSUE THREAD

**Issue by ProfDrVinz** [Tawling/MultiPause#4]
When i start the game, in the smapi cmd, it says it skips a mod with warning because MultiPause.dll is missing. How can i fix that? Thx for your help.

**Comment by ProfDrVinz** [comment]
LMAO, just wrote it, after trying to fix it for 20 minutes, created an account and now i fixed it. I downloaded the MultiPause-Master file and not the Mod file. Sorry, my fault...

**Comment by Velgus** [comment]
Note that the last "Release" here is not actually compatible with the latest version of SDV (1.5.X). You actually have to compile the latest master code changes in Visual Studio for a version that will work with some of the changes there - this includes a couple pull requests that updated the code for SDV 1.5.X and local split-screen coop compatibility.

I did so for myself, and if you trust my files you can download them here:
[MultiPause.zip](https://github.com/Tawling/MultiPause/files/6300114/MultiPause.zip)
