### ISSUE TITLE
Code repository has no license

### ISSUE THREAD

**Issue by Treeways** [Tawling/MultiPause#8]
I'd like to take a crack at fixing some of these issues myself. However it's not clear if I'm good to fork this code. (This makes maintaining unlicensed mods questionable.) This has been an important point brought up among the SDV community.

Is it okay if I make edits to the mod? If so, then thanks! Also, then you could consider adding some source of open source license to the repo so it's much more clear, such as the MIT or a GPL license. Thanks.

**Comment by Tawling** [comment]
That would be great. I'll add a license. I wish I had the time to work on this right now myself.

**Comment by Tawling** [comment]
MPL 2.0 added.
